version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=supersecretpassword
  vlack-api:
    build:
      context: ./vlack-api
    # image: unmidi/vlack-api
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__DefaultConnection: "User ID=postgres;Password=supersecretpassword;Server=postgres;Port=5432;Database=vlackdb;Integrated Security=true;Pooling=true;"
    depends_on:
      - postgres
  vlack-client:
    build:
      context: ./vlack
    # image: unmidi/vlack-client
    ports:
      - "5000:80"
